baseURL = 'https://learn-go-with-tests-arabic.pages.dev/'
languageCode = 'ar-sa'
title = 'تعلم Go مع الاختبارات'
theme = 'hugo-book'
defaultContentLanguage = 'ar'
defaultContentLanguageInSubdir = true
[languages]
  [languages.ar]
    languageDirection = 'rtl'
    weight = 1
