baseURL = 'https://learn.golangar.dev/'
languageCode = 'ar-sa'
title = 'تعلم Go مع الاختبارات'
theme = 'hextra'
defaultContentLanguage = 'ar'
defaultContentLanguageInSubdir = true

[languages]
  [languages.ar]
    languageDirection = 'rtl'
    weight = 1

[[menu.main]]
identifier = "الكتاب"
name = "لنبدأ القراءة"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "Search"
weight = 5
  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 6
url = "https://github.com/EssaAlshammri/learn-go-with-tests-arabic"
  [menu.main.params]
  icon = "github"

[params.navbar]
displayTitle = true
displayLogo = true
  [params.navbar.logo]
  path = "images/icon.png"
  link = "/ar/docs"
  width = 20
  height = 20

[params.editURL]
enable = true
base = "https://github.com/EssaAlshammri/learn-go-with-tests-arabic/edit/main/content/"

